### ISSUE TITLE
Arborescence

### ISSUE THREAD

**Issue by emchateau** [ouvroir/website#1]
- Home / Accueil
- - Actualités récentes
- - Projets en vedette
- - Rester en contact
- - Logos, etc.
- News / Actualités
- - Blogs
- - Events / Événements
- - Compte rendu de réunion caché par défaut (selection filtre)
- Projects / Projets
- Services / Services
- - ressources
- - réservations
- - liens vers la charte
- About / À propos
- - Introduction / Présentation
- - Team / Équipe
- - Charter / Charte de fonctionnement

**Comment by WilliamDiakite** [comment]
Archives pour la [veille](https://github.com/ouvroir/veille)

**Comment by WilliamDiakite** [comment]
Ajout financement sur la page d'accueil ?
