### ISSUE TITLE
Ouvrir les liens externes dans une autre fenêtre

### ISSUE THREAD

**Issue by emchateau** [ouvroir/website#11]
Ouvrir une nouvelle fenêtre quand il s’agit de lien externe (je sais que ce n’est pas toujours recommandé).
En tous les cas pour le Google Doc des réservations en ligne. 

HTML target="_blank" 
Ajouter un rel="noreferrer noopener" (permet d'éviter un type d'hameçonnage (phishing) connu sous le nom de [tabnabbing](https://www.leblogduhacker.fr/le-tabnabbing-une-attaque-par-phishing-evoluee/) (vol d'onglet).)

cf. https://www.freecodecamp.org/french/news/comment-utiliser-html-pour-ouvrir-un-lien-dans-un-nouvel-onglet/

**Comment by WilliamDiakite** [comment]
Issue fermée avec le dernier commit.
