### ISSUE TITLE
Typo et reformulation (page accueil)

### ISSUE THREAD

**Issue by emchateau** [ouvroir/website#12]
"En soutient aux communautés étudiantes et professorales de l'Université de Montréal, l’Ouvroir offre plusieurs services"
>
L’Ouvroir offre plusieurs services en soutien en appui de la communauté de recherche en muséologie et histoire de l’art tant pour les étudiant·e·s que pour les professeur·e·s

**Comment by WilliamDiakite** [comment]
Issue fermée avec le dernier commit.
