### ISSUE TITLE
Où se trouvent les contenus des pages service et à propos ?

### ISSUE THREAD

**Issue by emchateau** [ouvroir/website#13]
Normalement tous les contenus éditoriaux du site étaient dans le répertoire labrouvoir pour qu’il n’y ait qu’un seul endroit où modifier le contenu. Où se trouve l’actuelle page services ? (pour apporter des correctifs)

**Comment by WilliamDiakite** [comment]
ici https://github.com/ouvroir/labouvroir/tree/main/lab/services
