### ISSUE TITLE
Encarts pour Clinique numérique, Fika (et club lecture?)

### ISSUE THREAD

**Issue by WilliamDiakite** [ouvroir/website#18]
La page d'accueil doit intégrer un caroussel pour annoncer les événements réccurents :
- Clinique numérique
- Fika,
- Club de lecture (à valider @lenaMK , @emchateau )

Chaque événement est lié à un fichier .md. 
Pour le  Fika et le club de lecture, il faudra mettre à jour les dates des événements (risque fréquent d'annulation)
Pour la Clinique numérique, la prochaine date est générée dynamiquement

**Comment by emchateau** [comment]
En fait pourquoi un carrousel ? Est-ce que cela ne devrait pas apparaître dans la liste des activités tout simplement. Surtout qu’à terme on voudra probablement proposer un calendrier. 

La question de la génération de l’information doit être me semble-t-il distinguée de son stockage. On pourrait très bien avoir dans les métadonnées d’un fichier pour chaque événement une liste de dates que l’on pourrait ajuster au besoin s’il y a une annulation. Pour éviter les listes à rallonge, on pourrait peut être le faire pour chaque année ?
