### ISSUE TITLE
Traduction: lister les contenus à traduire, choisir ceux à laisser en français

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/website#3]

**Comment by WilliamDiakite** [comment]
Pour le moment mieux il vaudrait mieux éviter de traduire les slugs des contenus qui en ont déjà (ie les projets). Il me semble que pour les projets j'ai déjà homogénéiser les slugs pour qu'ils aient une valeure identique peu importe la langue. 

À rediscuter

**Comment by lenaMK** [comment]
proposition: ne pas traduire les événements puisqu'ils ont lieu en français

**Comment by lenaMK** [comment]
la traduction des métadonnées de la page en est faite, à relire si possible mais ça peut attendre
