### ISSUE TITLE
Créer des fiches md pour les anciens événements

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/website#4]
https://mobilizon.fr/@ouvroir_lab/events?showPassedEvents=true

**Comment by WilliamDiakite** [comment]
J'ajoute une priorité élevée. Il vaut mieux ne pas déployer le site sans plus contenu.

**Comment by lenaMK** [comment]
[#7b71d7d8d19637e6c5c1608d08c1325660c5f2e5](version en français)
est-ce qu'on crée des fiches pour les événements récurrents? (fika, clinique numérique, réunions hebdomadaires)

**Comment by lenaMK** [comment]
créer des fiches en pour traduire les métadonnées (résumé)

**Comment by lenaMK** [comment]
on va créer des encadrés distincts pour les activités récurrentes sur la page d'accueil

**Comment by WilliamDiakite** [comment]
> on va créer des encadrés distincts pour les activités récurrentes sur la page d'accueil

La #18 est ouverte pour la suite du travail.
