### ISSUE TITLE
Mettre à jour le lien pur la réservation d'espace de travail

### ISSUE THREAD

**Issue by emchateau** [ouvroir/website#53]
https://docs.google.com/spreadsheets/d/11EBiGa9AELoJt5j9KANnbXz3EGMhc8vrqQBaHLwTkfo/edit#gid=0

**Comment by WilliamDiakite** [comment]
C'est mis à jour !
À l'avenir, pourrait-on ouvrir les issues liées au contenu dans `labouvroir` directement ? Autrement je ne peux pas référencer les commits. Ce n'est pas un drame mais c'est dommage.

**Comment by emchateau** [comment]
Oui en effet, je te prie de m’excuser.
Pour info, on peut maintenant faire le transfert des issues (en bas à droite).
Amitiés,
