### ISSUE TITLE
Ajout d'une section pour les événements récurents

### ISSUE THREAD

**Issue by WilliamDiakite** [ouvroir/website#55]
Nous avions en déjà parlé mais il pourrait intéressant d'ajouter des sections concernant les événements récurrents de l'Ouvroir (ie. clinique numérique, sessions de rédaction) sur la home page. 

On pourrait par exemple avoir le déroulé suivant : 
- Hero menu avec présentation du laboratoire
- Section services
- Événements récurrents
- Les événements à venir
- Les projets
- Le bandeau de financement
- (footer)

**Comment by emchateau** [comment]
Les événements récurrents devraient apparaître dans la liste d’actualités. Ne pourrait-on pas créer un type d’actualités à dates multiples et n’afficher que les 1 ou 2 prochaines dates à venir ?
à discuter avec Zoë

**Comment by ZoeRenaudie** [comment]
William l'a mis en place mais je n'ai pas l'impression que ça fonctionne.
