### ISSUE TITLE
Traitement des titres dans les contenus éditoriaux (blogs et ressources)

### ISSUE THREAD

**Issue by emchateau** [ouvroir/website#65]
Une question que je me posais en regardant les contenus rédigés. On n’utilise pas de titre de niveau 1 dans les articles de blog et les ressources. Que se passe-t-il si on en met un ?

**Comment by emchateau** [comment]
C’était aussi mon sentiment.
Donc prochain round.

**Comment by WilliamDiakite** [comment]
Les titres vont être prochainement remis dans le corps du texte markdown pour plus de clareté.
