### ISSUE TITLE
Website fail to deploy

### ISSUE THREAD

**Issue by ZoeRenaudie** [ouvroir/website#68]
Le site n'arrive pas à se deployer depuis lundi dernier mais je n'ai pas l'impression que ce soit mes fichiers qui bloquent. Help needed pleaaase

**Comment by emchateau** [comment]
Visiblement l’erreur est la suivante :

Error: 500 /actualites (linked from /accueil)

Pour plus tard : To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender

**Comment by emchateau** [comment]
```txt
✓ built in 914ms
  301 / -> /accueil
[layout.build] fetching /accueil
[layout.build] fetching /actualites
[layout.build] fetching /actualites
TypeError: Cannot read properties of undefined (reading 'length')
    at file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/chunks/ContentList.js:181:568
    at Object.$$render (file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/chunks/ssr.js:56:18)
    at file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/chunks/ContentList.js:287:62
    at each (file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/chunks/ssr.js:26:12)
    at file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/chunks/ContentList.js:286:20
    at Object.$$render (file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/chunks/ssr.js:56:18)
    at file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/entries/pages/_news_news_/_page.svelte.js:18:218
    at Object.$$render (file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/chunks/ssr.js:56:18)
    at Object.default (file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/chunks/internal.js:82:97)
    at file:///Users/emmanuelchateau/ouvroir/website/.svelte-kit/output/server/entries/pages/_layout.svelte.js:270:39

node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /actualites (linked from /accueil)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///Users/emmanuelchateau/ouvroir/website/node_modules/@sveltejs/kit/src/core/config/options.js:203:13
    at file:///Users/emmanuelchateau/ouvroir/website/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:71:25
    at save (file:///Users/emmanuelchateau/ouvroir/website/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:419:4)
    at visit (file:///Users/emmanuelchateau/ouvroir/website/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:242:3)

Node.js v23.1.0
```

**Comment by ZoeRenaudie** [comment]
Chat gpt : 
Ce message d’erreurs contient plusieurs avertissements concernant l’accessibilité, les propriétés non utilisées, et des problèmes avec les modules. Voici comment aborder chaque type de message :

1. **Champ `svelte` manquant dans `svelte-carousel`** : Cela signifie que `svelte-carousel` manque d'une condition d'exportation. Pour résoudre cela, consultez les instructions [ici](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition), ou essayez de mettre à jour ou remplacer le package par un autre si possible.

2. **Propriétés exportées non utilisées** : Par exemple, `addPattern` est une propriété exportée qui n’est pas utilisée. Si vous n’avez pas besoin de cette propriété, supprimez-la. Sinon, exportez-la sous la forme `export const addPattern` si elle est seulement référencée en externe.

3. **Sélecteurs CSS non utilisés** : Les messages concernant `.container` ou `.tags-container` indiquent des classes non appliquées dans le HTML. Vérifiez leur utilisation dans votre code ou supprimez-les si elles ne sont plus nécessaires.

4. **Problèmes d’accessibilité** :
   - `autofocus`: Évitez `autofocus` pour améliorer l'accessibilité.
   - Attribut `on:click` sur un `<div>` : Ajoutez une gestion des événements clavier pour les éléments non interactifs (comme `on:keydown` ou utilisez `<button>` avec le rôle approprié).

5. **Erreur `handleError` non exporté** : Vérifiez votre fichier `src/hooks.client.ts` pour voir si `handleError` est bien exporté. Ajoutez `export` devant la fonction si elle est destinée à être utilisée ailleurs.

En appliquant ces ajustements, vous devriez pouvoir corriger les avertissements et erreurs et faire fonctionner votre site.

**Comment by emchateau** [comment]
Le site est de nouveau en ligne.
J’ai fait une révision générale des métadonnées des compte-rendus. Je pense que William travaillait avec une version antérieure du répertoire Labrouvoir. Il manquait des clefs "description" dans le Yaml de certains articles publiés.
