### ISSUE TITLE
Licence Font Awesome

### ISSUE THREAD

**Issue by WilliamDiakite** [ouvroir/website#8]
@emchateau, est-ce que ça vaudrait le coup d'acheter une licence fontAwesome (qui pourrait également servir pour d'autres projets dont celui de la Chaire) ?

Autrement il faudrait changer les icones en place.

**Comment by WilliamDiakite** [comment]
La licence (annuelle!!) est trop chère. Il faut trouver des icones open source

**Comment by emchateau** [comment]
On peut cependant payer si une somme ponctuelle. Le problème est la récurrence sur FontAwesome (rente). J‘aime bien boxions, feathericons, ionic. Est-ce que tu as une idée des symboles à chercher ?

**Comment by WilliamDiakite** [comment]
J'aime bien boxicon aussi, je pensais d'ailleurs partir avec ça !

> Est-ce que tu as une idée des symboles à chercher ?

Oui j'ai jeter un oeil rapide (boxicon particulièrement) et je crois qu'il y a tout ce qu'il faut !
